.travis.yml:
  secure: "NY8Ff5WxEBSitFLOeRDAwkp48+HQuDbqGT96nB+5FTfiTTS/yY134hsWlfnEVrFNvC09f36wh8XXEkW6cTgIBdfeb3ZLVkUg545Ae0m46RouPwwl6goo9fsGEEBoJXhln9gk6UQpkjbKh9tCDLij3WKDxrDUIb/8Xlp3WkzAhCQ="
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
spec/acceptance/nodesets/centos-65-x64-docker.yml:
  delete: true
spec/acceptance/nodesets/centos-65-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-7-x64-docker.yml:
  delete: true
spec/acceptance/nodesets/debian-7-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-73-x64.yml:
  delete: true
spec/acceptance/nodesets/default.yml:
  delete: true
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-server-1404-x64-docker.yml:
  delete: true
